version: 0.2

env:
  parameter-store:
    DISCORD_TOKEN: DISCORD_TOKEN
phases:
  install:
    runtime-versions:
      golang: 1.16
  build:
    commands:
      - cd $CODEBUILD_SRC_DIR && go build ./cmd/albumbot/main.go
  post_build:
    commands:
      - cd $CODEBUILD_SRC_DIR && touch .env && echo DISCORD_TOKEN=$DISCORD_TOKEN > .env
artifacts:
  files:
    - "**/*"
