name: Test&Format

on:
  pull_request:
    branches: [main]

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Setup Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.16

    - name: Test
      run: go test -v ./...

    - name: Format
      run: go fmt ./...

    - name: Commit
      uses: stefanzweifel/git-auto-commit-action@v4.13.1
      with:
        commit_message: "PR作成時の自動Commit"
        branch: ${{ github.head_ref }}