name: Test&Format

on:
  pull_request:
    branches: [main]

env:
  AWS_REGION: ap-northeast-1

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Setup Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.16

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ env.AWS_REGION }}

    - name: Test
      run: |
        export TABLE_NAME=Albums
        go test -v ./album.go ./album_test.go

    - name: Format
      run: go fmt ./...

    - name: Commit
      uses: stefanzweifel/git-auto-commit-action@v4.13.1
      with:
        commit_message: "PR作成時の自動Commit"
        branch: ${{ github.head_ref }}